# Form implementation generated from reading ui file 'loginUI.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import mysql.connector as mc
from PyQt6.QtGui import QPixmap

dbconfig = {
    'user': 'root',
    'password': 'admin123',
    'host': '127.0.0.1',
    'database': 'hikaru'
}

class log_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1104, 501)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../sushiVent0.002/images/sushi-60.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("background-color:rgb(244, 249, 252);\n"
"")
        self.label_bdname = QtWidgets.QLabel(Dialog)
        self.label_bdname.setGeometry(QtCore.QRect(610, 40, 401, 61))
        self.label_bdname.setStyleSheet("color:black;")
        self.label_bdname.setObjectName("label_bdname")
        self.input_nom = QtWidgets.QLineEdit(Dialog)
        self.input_nom.setGeometry(QtCore.QRect(530, 100, 551, 41))
        self.input_nom.setStyleSheet("background-color: rgba(255, 255, 255, 160);\n"
"border-radius: 15px;\n"
"")
        self.input_nom.setObjectName("input_nom")
        self.pushButton_exec = QtWidgets.QPushButton(Dialog)
        self.pushButton_exec.setGeometry(QtCore.QRect(550, 340, 531, 61))
        self.pushButton_exec.setStyleSheet("background-color: rgb(0, 123, 255);\n"
"border-radius: 15px;\n"
"color:white;\n"
"font: 24pt \".AppleSystemUIFont\";")
        self.pushButton_exec.setObjectName("pushButton_exec")
        self.label_out = QtWidgets.QLabel(Dialog)
        self.label_out.setGeometry(QtCore.QRect(510, 410, 681, 51))
        self.label_out.setStyleSheet("")
        self.label_out.setText("")
        self.label_out.setObjectName("label_out")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 501, 501))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images/hikaru.png"))
        self.label.setObjectName("label")
        self.input_pass = QtWidgets.QLineEdit(Dialog)
        self.input_pass.setGeometry(QtCore.QRect(540, 240, 551, 41))
        self.input_pass.setStyleSheet("background-color: rgba(255, 255, 255, 160);\n"
"border-radius: 15px;\n"
"")
        self.input_pass.setObjectName("input_pass")
        self.label_bdname_2 = QtWidgets.QLabel(Dialog)
        self.label_bdname_2.setGeometry(QtCore.QRect(600, 170, 401, 61))
        self.label_bdname_2.setStyleSheet("color:black;")
        self.label_bdname_2.setObjectName("label_bdname_2")
        self.pushButton_exec.clicked.connect(self.login)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "SushiTest"))
        self.label_bdname.setText(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:48pt;\">Username</span></p></body></html>"))
        self.pushButton_exec.setText(_translate("Dialog", "Login"))
        self.label_bdname_2.setText(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:48pt;\">Password</span></p></body></html>"))


    def login(self):
        try:
            mydb = mc.connect(**dbconfig)
            user = self.input_nom.text()
            password = self.input_pass.text()
            # bytePwd = password.encode('utf-8')
            # mySalt = bcrypt.gensalt()
            # hash = bcrypt.hashpw(bytePwd, mySalt)
            # pwd = hash.decode("utf-8")
            # print(pwd)

            mycursor = mydb.cursor()
            query = "SELECT username,password from users where username = '" + user +"'and password = '" + password +"'"

            mycursor.execute(query)
            result = mycursor.fetchone()
            if result == None:
                print("fail")
            else:
                query2 = "SELECT is_admin from users where username like '"+ user + "'"
                mycursor.execute(query2)
                result2 = mycursor.fetchone()
                if result2[0] == 1:
                    try:
                        query3 = "UPDATE users SET is_log = 'on' WHERE username = '" + user + "'"
                        mycursor.execute(query3)
                        mydb.commit()
                    except mc.Error as e:
                        print(e)


                elif result2[0] == 1:
                    try:
                        query4 = "UPDATE users SET is_log = 'on' WHERE username = '" + user + "'"
                        mycursor.execute(query4)
                        mydb.commit()
                        self.label_2.setText("estas log como ADMIN")
                    except mc.Error as e:
                        print(e)
        except mc.Error as e:
            self.label_2.setText("Error {}".format(e))
