# Form implementation generated from reading ui file 'newOrden.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Add_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(575, 227)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.line_pl = QtWidgets.QLineEdit(Dialog)
        self.line_pl.setGeometry(QtCore.QRect(20, 30, 491, 31))
        self.line_pl.setObjectName("line_pl")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 121, 21))
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(520, 30, 41, 31))
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/search-50.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.list_orden_up = QtWidgets.QListWidget(Dialog)
        self.list_orden_up.setGeometry(QtCore.QRect(20, 70, 491, 91))
        self.list_orden_up.setObjectName("list_orden_up")
        self.pushButton_finish_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_finish_2.setGeometry(QtCore.QRect(70, 180, 161, 31))
        self.pushButton_finish_2.setObjectName("pushButton_finish_2")
        self.pushButton_create_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_create_2.setGeometry(QtCore.QRect(300, 180, 161, 31))
        self.pushButton_create_2.setObjectName("pushButton_create_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Añadir platillo"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p>Añadir primer plato</p></body></html>"))
        self.pushButton_finish_2.setText(_translate("Dialog", "Terminar"))
        self.pushButton_create_2.setText(_translate("Dialog", "Crear"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Add_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
